name: Devnull
url: http://devnull.absolventa.de
description: The blog of the ABSOLVENTA Dev Team

permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: pygments
markdown: kramdown

gems:
  - jekyll-sitemap

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'CNAME']

colors:
  highlight: '#0F0'

theme:
  name: Devnull
  highlight_color: '#0d586b'
  gauges_key: '52567bcc613f5d6ad7000042'

  social:
    github: Absolventa
    twitter: ABSOLVENTA

authors:
  carp:
    display_name: Carsten Zimmermann
    googleplus: https://plus.google.com/u/0/101728608052847168461
    gravatar: d7cb4a1c32b57046567d5009e366f0cf
  rbn:
    display_name: Robin Neumann
    googleplus: https://plus.google.com/u/0/106424233859444481952
    gravatar: 8af2b98f12cb74818f42d3e5ac50d198
  dev:
    display_name: ABSOLVENTA Dev-Team
