name: Devnull
url: http://devnull.absolventa.de
description: The blog of the ABSOLVENTA Dev Team

permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: rouge
markdown: kramdown

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'CNAME']

colors:
  highlight: '#0F0'

theme_settings:
  name: Devnull
  highlight_color: '#0d586b'
  gauges_key: '52567bcc613f5d6ad7000042'

  social:
    github: Absolventa
    twitter: ABSOLVENTA

authors:
  carp:
    display_name: Carsten Zimmermann
    googleplus: https://plus.google.com/u/0/101728608052847168461
    gravatar: d7cb4a1c32b57046567d5009e366f0cf
    twitter: https://twitter.com/carpgezwitscher
  rbn:
    display_name: Robin Neumann
    googleplus: https://plus.google.com/u/0/106424233859444481952
    gravatar: 8af2b98f12cb74818f42d3e5ac50d198
    twitter: https://twitter.com/openhorsecode
  axlwaii:
    display_name: Markus Waitl
    googleplus: https://plus.google.com/u/1/110651366557579872096
    gravatar: 72a8ad3ea51a0b1d5e95f1a2827f3350
    twitter: https://twitter.com/axlwaii
  dev:
    display_name: ABSOLVENTA Dev-Team
